
"Values"
{
	"BaseClass"
	{
		"ability_datadriven"	"#AbilityDataDriven"
		"ability_lua"			"#AbilityLua"
	}
	
	"var_type"
	{
		"FIELD_INTEGER"			"#FieldInteger"
		"FIELD_FLOAT"			"#FieldFloat"
	}

	"AbilityUnitTargetTeam"
	{
		"DOTA_UNIT_TARGET_TEAM_ENEMY"	"descr"
		"DOTA_UNIT_TARGET_TEAM_FRIENDLY"	"descr"
	}

	"AbilityBehavior"
	{
		"DOTA_ABILITY_BEHAVIOR_PASSIVE"	"Descr"
		"DOTA_ABILITY_BEHAVIOR_HIDDEN"	"Descr"
	}
}