//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDota2EditorWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDota2EditorWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abilities.
        /// </summary>
        public static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create KV block.
        /// </summary>
        public static string CreateGUIKVBlock {
            get {
                return ResourceManager.GetString("CreateGUIKVBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create KV item.
        /// </summary>
        public static string CreateGUIKVItem {
            get {
                return ResourceManager.GetString("CreateGUIKVItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create object.
        /// </summary>
        public static string CreateObject {
            get {
                return ResourceManager.GetString("CreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name is empty!.
        /// </summary>
        public static string CreateObjectNameEmpty {
            get {
                return ResourceManager.GetString("CreateObjectNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteItemGUI {
            get {
                return ResourceManager.GetString("DeleteItemGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete object.
        /// </summary>
        public static string DeleteObject {
            get {
                return ResourceManager.GetString("DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s not an addon folder!.
        /// </summary>
        public static string ErrorLoadAddonNoFindedAddoninfoTxt {
            get {
                return ResourceManager.GetString("ErrorLoadAddonNoFindedAddoninfoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heroes.
        /// </summary>
        public static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Folder.
        /// </summary>
        public static string InvalidFolder {
            get {
                return ResourceManager.GetString("InvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text changed.
        /// </summary>
        public static string ItemTextChangedGUI {
            get {
                return ResourceManager.GetString("ItemTextChangedGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string MainMenuAbout2 {
            get {
                return ResourceManager.GetString("MainMenuAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string MainMenuClose {
            get {
                return ResourceManager.GetString("MainMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string MainMenuExit {
            get {
                return ResourceManager.GetString("MainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object views.
        /// </summary>
        public static string MainMenuObjectViews {
            get {
                return ResourceManager.GetString("MainMenuObjectViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string MainMenuOpen {
            get {
                return ResourceManager.GetString("MainMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string MainMenuSave {
            get {
                return ResourceManager.GetString("MainMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send bug or offer.
        /// </summary>
        public static string MainMenuSendBug {
            get {
                return ResourceManager.GetString("MainMenuSendBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows.
        /// </summary>
        public static string MainMenuWindows {
            get {
                return ResourceManager.GetString("MainMenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move down.
        /// </summary>
        public static string MoveDownGUI {
            get {
                return ResourceManager.GetString("MoveDownGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move folder/object.
        /// </summary>
        public static string MoveFolderObject {
            get {
                return ResourceManager.GetString("MoveFolderObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move up.
        /// </summary>
        public static string MoveUpGUI {
            get {
                return ResourceManager.GetString("MoveUpGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New folder .
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not saved.
        /// </summary>
        public static string NotSavedCapture {
            get {
                return ResourceManager.GetString("NotSavedCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want save?.
        /// </summary>
        public static string NotSavedDialogText {
            get {
                return ResourceManager.GetString("NotSavedDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abils.
        /// </summary>
        public static string ObjectViewTabName_Abilities {
            get {
                return ResourceManager.GetString("ObjectViewTabName_Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AbilsOver.
        /// </summary>
        public static string ObjectViewTabName_AbilitioesOverrite {
            get {
                return ResourceManager.GetString("ObjectViewTabName_AbilitioesOverrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heroes.
        /// </summary>
        public static string ObjectViewTabName_Heroes {
            get {
                return ResourceManager.GetString("ObjectViewTabName_Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        public static string ObjectViewTabName_Items {
            get {
                return ResourceManager.GetString("ObjectViewTabName_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Units.
        /// </summary>
        public static string ObjectViewTabName_Units {
            get {
                return ResourceManager.GetString("ObjectViewTabName_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string ObjViewPanelRedoDescription {
            get {
                return ResourceManager.GetString("ObjViewPanelRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string ObjViewPanelUndoDescription {
            get {
                return ResourceManager.GetString("ObjViewPanelUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename folder.
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename object.
        /// </summary>
        public static string RenameObject {
            get {
                return ResourceManager.GetString("RenameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This name is already using!.
        /// </summary>
        public static string RenameThisNameAlreadyUsing {
            get {
                return ResourceManager.GetString("RenameThisNameAlreadyUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add editor header to all files.
        /// </summary>
        public static string SettingsAddEditorHeader {
            get {
                return ResourceManager.GetString("SettingsAddEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start program with:.
        /// </summary>
        public static string SettingsCaptureStartProgramWithEditor {
            get {
                return ResourceManager.GetString("SettingsCaptureStartProgramWithEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dota 2 path.
        /// </summary>
        public static string SettingsDotaPath {
            get {
                return ResourceManager.GetString("SettingsDotaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        public static string SettingsFont {
            get {
                return ResourceManager.GetString("SettingsFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bold.
        /// </summary>
        public static string SettingsFontBold {
            get {
                return ResourceManager.GetString("SettingsFontBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italic.
        /// </summary>
        public static string SettingsFontItalic {
            get {
                return ResourceManager.GetString("SettingsFontItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underline.
        /// </summary>
        public static string SettingsFontUnderline {
            get {
                return ResourceManager.GetString("SettingsFontUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide standarts Dota 2 projects.
        /// </summary>
        public static string SettingsHideStandartDotaProjects {
            get {
                return ResourceManager.GetString("SettingsHideStandartDotaProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments:.
        /// </summary>
        public static string SettingsHightComments {
            get {
                return ResourceManager.GetString("SettingsHightComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default text:.
        /// </summary>
        public static string SettingsHightDefaultText {
            get {
                return ResourceManager.GetString("SettingsHightDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key:.
        /// </summary>
        public static string SettingsHightKey {
            get {
                return ResourceManager.GetString("SettingsHightKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key-block:.
        /// </summary>
        public static string SettingsHightKeyBlock {
            get {
                return ResourceManager.GetString("SettingsHightKeyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hightlighting colors.
        /// </summary>
        public static string SettingsHightlightingColors {
            get {
                return ResourceManager.GetString("SettingsHightlightingColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value:.
        /// </summary>
        public static string SettingsHightValue {
            get {
                return ResourceManager.GetString("SettingsHightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value-numbers:.
        /// </summary>
        public static string SettingsHightValueNumbers {
            get {
                return ResourceManager.GetString("SettingsHightValueNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save and open last opened objects.
        /// </summary>
        public static string SettingsLoadSaveOpenedObjects {
            get {
                return ResourceManager.GetString("SettingsLoadSaveOpenedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common.
        /// </summary>
        public static string SettingsMenuCommon {
            get {
                return ResourceManager.GetString("SettingsMenuCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highlighting.
        /// </summary>
        public static string SettingsMenuHighlighting {
            get {
                return ResourceManager.GetString("SettingsMenuHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open last opened project.
        /// </summary>
        public static string SettingsOpenLastOpenedProject {
            get {
                return ResourceManager.GetString("SettingsOpenLastOpenedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Primary editor.
        /// </summary>
        public static string SettingsPrimaryEditor {
            get {
                return ResourceManager.GetString("SettingsPrimaryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Both editors.
        /// </summary>
        public static string SettingsRadioStartWithBothEditors {
            get {
                return ResourceManager.GetString("SettingsRadioStartWithBothEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LUA editor.
        /// </summary>
        public static string SettingsRadioStartWithLuaEditor {
            get {
                return ResourceManager.GetString("SettingsRadioStartWithLuaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object editor.
        /// </summary>
        public static string SettingsRadioStartWithObjectEditor {
            get {
                return ResourceManager.GetString("SettingsRadioStartWithObjectEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset windows places.
        /// </summary>
        public static string SettingsResetWindowsPlaces {
            get {
                return ResourceManager.GetString("SettingsResetWindowsPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show full lua file names.
        /// </summary>
        public static string SettingsShowFullLuaFileNames {
            get {
                return ResourceManager.GetString("SettingsShowFullLuaFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Common.
        /// </summary>
        public static string SettingsTabCommon {
            get {
                return ResourceManager.GetString("SettingsTabCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hightlightring KV.
        /// </summary>
        public static string SettingsTabHightlighting {
            get {
                return ResourceManager.GetString("SettingsTabHightlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hightlighting lua.
        /// </summary>
        public static string SettingsTabHightlightingLua {
            get {
                return ResourceManager.GetString("SettingsTabHightlightingLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main page.
        /// </summary>
        public static string SettingsTabMainPage {
            get {
                return ResourceManager.GetString("SettingsTabMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings lua.
        /// </summary>
        public static string SettingsTabSettingsLua {
            get {
                return ResourceManager.GetString("SettingsTabSettingsLua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set all settings to default?.
        /// </summary>
        public static string SetToDefault {
            get {
                return ResourceManager.GetString("SetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string SetToDefaultCapture {
            get {
                return ResourceManager.GetString("SetToDefaultCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set settings to settings with programm loaded?.
        /// </summary>
        public static string SetToStartSettings {
            get {
                return ResourceManager.GetString("SetToStartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set to start settings.
        /// </summary>
        public static string SetToStartSettingsCapture {
            get {
                return ResourceManager.GetString("SetToStartSettingsCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a folder with an addoninfo.txt.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text contains errors! Do you want anyway close it? Any changes will not saved!!!.
        /// </summary>
        public static string TextContainErrors {
            get {
                return ResourceManager.GetString("TextContainErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text contains errors.
        /// </summary>
        public static string TextContainErrorsCapture {
            get {
                return ResourceManager.GetString("TextContainErrorsCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
